---
name: Check Spelling

on: push

jobs:
  build:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper 
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Check Spelling
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
