---
name: CI Tests
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install --save-dev jest
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
